import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import styles from './main.module.css';
//import styles from "styles.modules.css"

export const metadata: Metadata = {
  title: "City Hacks",
  description: "Generated by create next app",
};

import { UserProvider } from '@auth0/nextjs-auth0/client';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
    <UserProvider>
    <body>
      <main className={styles.container}>
      {children}
      </main>
      </body>
  </UserProvider>
  </html>
  )
}



// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//     <UserProvider>
//       <body>{children}</body>
//     </UserProvider>
//     </html>
//   );
// }
